name: Pull request
on:
  pull_request:
    paths:
      - 'libs/**'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      direct-projects: ${{ steps['set-direct-projects'].outputs['direct-projects'] }}
      dependent-projects: ${{ steps['set-dependent-projects'].outputs['dependent-projects'] }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install Rush
        run: node common/scripts/install-run-rush.js install --purge
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set directly affected projects by PR
        working-directory: ${{ github.workspace }}/tools/affected-projects
        id: set-direct-projects
        run: echo "::set-output name=direct-projects::$(node dist/index.js --json)"
      - name: Set transitively affected projects by PR
        working-directory: ${{ github.workspace }}/tools/affected-projects
        id: set-dependent-projects
        run: echo "::set-output name=dependent-projects::$(node dist/index.js --json --dependents)"

  deploy-app:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs['dependent-projects'])}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      #      - name: Log direct projects
      #        run: echo ${{needs.setup.outputs['direct-projects']}}
      #      - name: Log dependent projects
      #        run: echo ${{needs.setup.outputs['dependent-projects']}}
      - run: |
          echo "${{ matrix.value }}"
      - uses: ./.github/actions/deploy
        with:
          app-name: ${{ matrix.value }}